// Listar niveles disponibles
export const GET_LISTA_NIVELES_DISPONIBLES_SUCCESS = 'GET_LISTA_NIVELES_DISPONIBLES_SUCCESS';
export const GET_LISTA_NIVELES_DISPONIBLES_FAIL = 'GET_LISTA_NIVELES_DISPONIBLES_FAIL';

// Crear nivel disponible
export const CREATE_NIVEL_DISPONIBLE_SUCCESS = 'CREATE_NIVEL_DISPONIBLE_SUCCESS';
export const CREATE_NIVEL_DISPONIBLE_FAIL = 'CREATE_NIVEL_DISPONIBLE_FAIL';

// Eliminar nivel disponible
export const DELETE_NIVEL_DISPONIBLE_SUCCESS = 'DELETE_NIVEL_DISPONIBLE_SUCCESS';
export const DELETE_NIVEL_DISPONIBLE_FAIL = 'DELETE_NIVEL_DISPONIBLE_FAIL';