export const GET_LISTA_NIVELES_SUCCESS = "GET_LISTA_NIVELES_SUCCESS"
export const GET_LISTA_NIVELES_FAIL = "GET_LISTA_NIVELES_FAIL"

export const GET_LISTA_NIVELES_BY_CREADOR_SUCCESS = "GET_LISTA_NIVELES_BY_CREADOR_SUCCESS"
export const GET_LISTA_NIVELES_BY_CREADOR_FAIL = "GET_LISTA_NIVELES_BY_CREADOR_FAIL"

export const GET_DETAILED_NIVEL_SUCCESS = "GET_DETAILED_NIVEL_SUCCESS"
export const GET_DETAILED_NIVEL_FAIL = "GET_DETAILED_NIVEL_FAIL"

export const GET_SEARCH_NIVEL_SUCCESS = "GET_SEARCH_NIVEL_SUCCESS"
export const GET_SEARCH_NIVEL_FAIL = "GET_SEARCH_NIVEL_FAIL"

export const CREATE_NIVEL_SUCCESS = "CREATE_NIVEL_SUCCESS";
export const CREATE_NIVEL_FAIL = "CREATE_NIVEL_FAIL";

export const DELETE_NIVEL_SUCCESS = "DELETE_NIVEL_SUCCESS";
export const DELETE_NIVEL_FAIL = "DELETE_NIVEL_FAIL";