# Generated by Django 4.2.11 on 2024-06-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nivel', '0001_initial'),
        ('creador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelesDisponibles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nivel.nivel_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creador.creador')),
            ],
        ),
    ]
