# Generated by Django 4.2.11 on 2024-06-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0001_initial'),
        ('creador', '0002_initial'),
        ('nivelesDisponibles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nivelesdisponibles',
            unique_together={('user', 'nivel')},
        ),
    ]
