# Generated by Django 4.2.11 on 2024-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivelesDisponibles', '0002_alter_nivelesdisponibles_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelesdisponibles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
