# Generated by Django 4.2.11 on 2024-05-28 10:11

import apps.nivel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_post',
            name='thumbnail',
            field=models.ImageField(max_length=500, upload_to=apps.nivel.models.nivel_thumbnail_directory),
        ),
    ]
