# Generated by Django 4.2.11 on 2024-06-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_post',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nivel_post',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
