# Generated by Django 4.2.11 on 2024-06-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0003_nivel_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivelpost_like_count', to='nivel.nivel_post')),
            ],
        ),
    ]
