# Generated by Django 4.2.11 on 2024-06-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creador', '0003_creador_likes_likecount'),
        ('nivel', '0004_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecount',
            name='creador',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='creador.creador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewcount',
            name='creador',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='creador.creador'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='likecount',
            unique_together={('nivel', 'creador')},
        ),
        migrations.AlterUniqueTogether(
            name='viewcount',
            unique_together={('nivel', 'creador')},
        ),
    ]
