# Generated by Django 4.2.11 on 2024-06-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0005_likecount_creador_viewcount_creador_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likecount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='viewcount',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='likecount',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='viewcount',
            name='creador',
        ),
    ]
